export const checklist = [
    {
      area: "FACHADA EXTERIOR",
        icon: "mdi:home",
        id: "fachada",
      checks: [
        "PAREDES EXTERIORES EN BUEN ESTADO",
        "PINTURA (PAREDES Y REJAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "CERRADURAS EN BUEN ESTADO (FUNCIONALES)",
        "BANQUETAS EN BUEN ESTADO (PINTURA E INFRAESTRUCTURA)",
        "RAMPAS EN BUEN ESTADO (PINTURA)",
      ],
    },
    {
      area: "COCHERA",
      icon: "mdi:car",
      id: "cochera",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES Y TECHOS SIN PRESENCIA DE HUMEDAD",
        "EQUIPO EXTERIOR EN BUENAS CONDICIONES (SILLAS Y MESAS EXTERIORES)",
        "BARANDALES DE SEGURIDAD EN BUEN ESTADO",
        "ILUMINACION FUNCIONAL (FOCOS)",
        "CINTA ANTIDERRAPANTE EN BUEN ESTADO",
      ],
    },
    {
      area: "RECEPCION",
        icon: "mdi:account",
        id: "recepcion",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PUERTA PRINCIPAL EN BUEN ESTADO",
        "PAREDES Y TECHOS SIN PRESENCIA DE HUMEDAD",
        "MOBILIARIO EN BUEN ESTADO (SOFAS Y TV)",
        "CERADURA FUNCIONAL",
        "ILUMINACION FUNCIONAL (FOCOS)",
      ],
    },
    {
      area: "AREA COMUN",
        icon: "mdi:account-multiple",
        id: "area-social",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "PUERTAS EN COLINDACIA EN BUEN ESTADO (PINTURA Y FUNCIONALIDAD)",
        "PINTURA",
        "VIDRIOS DE VENTANAS ALTAS LIMPIAS",
        "PERSIANAS FUNCIONALES Y EN BUEN ESTADO",
        "CONTACTOS DE LUZ EN BUEN ESTADO Y FUNCIONALES",
        "EXTENSIONES OCULTAS Y EN BUEN ESTADO",
        "MOBILIARIO EN BUEN ESTADO (SOFAS Y TV)",
        "ILUMINACION FUNCIONAL (FOCOS)",
        "MINI SPLITS EN BUEN ESTADO (SIN RUIDO Y FILTROS LIMPIOS)",
        "EXTINTORES INSTALADOS",
        "DIFUSOR FUNCIONANDO",
      ],
    },
    {
      area: "COMEDOR",
        icon: "mdi:food",
        id: "comedor",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "PUERTAS EN COLINDACIA EN BUEN ESTADO (PINTURA Y FUNCIONALIDAD)",
        "PINTURA",
        "CONTACTOS DE LUZ EN BUEN ESTADO Y FUNCIONALES",
        "EXTENSIONES OCULTAS Y EN BUEN ESTADO",
        "MOBILIARIO EN BUEN ESTADO (MESAS Y SILLAS)",
        "ILUMINACION FUNCIONAL (FOCOS)",
        "MINI SPLIT SIN RUIDOS Y FILTROS LIMPIOS",
        "EXTINTORES INSTALADOS",
      ],
    },
    {
      area: "LAVANDERIA",
        icon: "mdi:washing-machine",
        id: "lavanderia",
      checks: [
        "CONEXIONES DE GAS EN BUEN ESTADO (MANGUERAS EN BUENAS CONDICIONES)",
        "CONEXIONES DE AGUA EN BUEN ESTADO (SIN FUGAS)",
        "CONTACTOS DE LUZ EN BUEN ESTADO",
        "FILTROS DE SECADORAS LIMPIOS",
        "FILTROS EXTERIORES DE SECADORA BIEN INSTALADOS",
        "REPISAS EN BUEN ESTADO",
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "DESAGUE SIN OBSTRUCCIONES",
        "ILUNIMACION FUNCIONAL (FOCOS)",
        "EXTINTORES INSTALADOS",
      ],
    },
    {
      area: "COCINA",
        icon: "mdi:stove",
        id: "cocina",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "MANGUERAS Y CONEXIONES DE GAS EN BUEN ESTADO",
        "EXTINTOR INSTALADO",
        "CONTACTOS DE LUZ EN BUEN ESTADO",
        "ILUNIMACION FUNCIONAL (FOCOS)",
        "REFRIGERADORES FUNCIONALES (PARTES EXTERIORES BAJAS Y DESAGUES LIMPIOS)",
        "MICROONDAS LIMPIO (PARTE TRASERA)",
        "CONEXIONES Y TUBERIAS DE AGUA EN BUEN ESTADO (SIN PRESENCIA DE FUGAS)",
        "FILTRO DE AGUA FUNCIONANDO CORRECTAMENTE",
        "TARJA DE COCINA EN BUEN ESTADO Y SELLADA",
        "EXTRACTOR LIMPIO Y FUNCIONANDO",
        "MOBILIARIO EN BUEN ESTADO Y FUNCIONAL (REPISAS Y PUERTAS)",
      ],
    },
    {
      area: "CUARTO DESPENSA",
        icon: "mdi:fridge",
        id: "despensa",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "ILUNIMACION FUNCIONAL (FOCOS)",
      ],
    },
    {
      area: "PASILLOS",
      icon: "mdi:walk",
        id: "pasillos",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "ILUNIMACION FUNCIONAL (FOCOS)",
        "CONTACTOS DE LUZ EN BUEN ESTADO",
        "EXTINTORES INSTALADOS",
      ],
    },
    {
      area: "HABITACIONES",
        icon: "mdi:bed",
        id: "habitaciones",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "ILUNIMACION FUNCIONAL (FOCOS)",
        "CONTACTOS EN BUEN ESTADO",
        "BASES DE CAMAS EN BUEN ESTADO",
        "CLOSETS EN BUEN ESTADO (PINTURA, BISAGRAS, RIELES, PUERTAS Y CAJONES)",
        "MINI SPLIT SIN RUIDOS Y FILTROS LIMPIOS",
        "VENTANAS EN BUEN ESTADO",
        "PERSIANAS EN BUEN ESTADO",
      ],
    },
    {
      area: "BAÑOS DE HABITACIONES",
        icon: "mdi:bathtub",
        id: "banos-habitaciones",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "ILUNIMACION FUNCIONAL (FOCOS)",
        "CONTACTOS EN BUEN ESTADO",
        "MANGUERAS Y CONEXIONES DE AGUA EN BUEN ESTADO",
        "DESAGUES COMPLETOS Y LIMPIOS",
        "SILLAS DE BAÑO EN BUENAS CONDICIONES (RUEDAS, TORNILLOS, TUERCAS, DESCANSABRAZOS Y SOPORTES DE ESPALDA)",
        "BARRAS DE SEGURIDAD EN BUEN ESTADO",
        "SOPORTE DE TOALLAS EN BUEN ESTADO",
      ],
    },
    {
      area: "BAÑOS COMUNES",
        icon: "mdi:toilet",
        id: "banos-comunes",
      checks: [
        "PAREDES Y TECHOS EN BUEN ESTADO (PINTURA Y GOTERAS)",
        "PAREDES SIN PRESENCIA DE HUMEDAD",
        "ILUNIMACION FUNCIONAL (FOCOS)",
        "CONTACTOS EN BUEN ESTADO",
        "GOTERO DE ESCUSADO FUNCIONANDO",
        "RETRETE SIN FUGAS",
        "PORTARROLLOS EN BUEN ESTADO",
        "MANGUERAS Y CONEXIONES DE AGUA EN BUEN ESTADO",
        "SOPORTE DE TOALLAS EN BUEN ESTADO",
      ],
    },
    {
      area: "JARDIN EXTERIOR",
        icon: "mdi:flower",
        id: "jardin-exterior",
      checks: [
        "PODADO",
        "SIN HOJAS EN PISO",
        "DESAGUES LIMPIOS",
        "PAREDES EXTERIORES EN BUEN ESTADO (PINTURA Y HUMEDAD)",
      ],
    },
    {
      area: "TECHOS",
        icon: "mdi:home-roof",
        id: "techos",
      checks: [
        "DESAGUES LIMPIOS",
        "IMPERMEABILIZANTE EN BUEN ESTADO",
        "INVERSORES FUNCIONANDO",
        "TECHOS LIMPIOS",
        "PANELES LIMPIOS",
        "COMPRESORES DE MINI SPLIT LIMPIOS",
        "COMPRESORES SIN VIBRACIONES",
      ],
    },
  ];

export  const cleaningChecklist = [
    {
      area: "COCHERA",
      checks: [
        "BARRER",
        "TRAPEAR",
        "LIMPIAR MESA",
        "LIMPIAR SILLAS",
        "BARRER BANQUETA",
      ],
    },
    {
      area: "RECEPCION",
      checks: [
        "BARRER",
        "TRAPEAR",
        "SACUDIR MOBILIARIO",
        "PUERTAS Y CRISTALES LIMPIOS",
      ],
    },
    {
      area: "AREA SOCIAL",
      checks: [
        "SACUDIR Y LIMPIAR MUEBLES",
        "BARRER (BAJO SILLONES)",
        "TRAPEAR (BAJO SILLONES)",
        "LIMPIAR VENTANAS",
      ],
    },
    {
      area: "AREA DE COMEDOR",
      checks: [
        "BARRER",
        "TRAPEAR",
        "LIMPIAR MESA",
        "LIMPIAR SILLAS",
        "SACUDIR Y LIMPIAR MUEBLES",
      ],
    },
    {
      area: "LAVANDERIA",
      checks: [
        "BARRER",
        "TRAPEAR",
        "QUIMICOS DE LIMPIEZA ORDENADOS",
        "LAVADORAS LIMPIAS (EXTERIOR)",
        "SECADORAS LIMPIAS (EXTERIOR)",
        "FILTROS DE SECADORA LIMPIOS",
        "ROPA ORDENADA Y COLGADA",
        "TRAPEADORES LIMPIOS Y EN SU LUGAR",
        "ESCOBAS LIMPIAS Y EN SU LUGAR",
        "RECOGEDORES LIMPIOS Y EN SU LUGAR",
        "REPISAS LIMPIAS",
        "SEPARAR Y LAVAR TOALLAS, PANTALONES, BLUSAS, CALCETINES, SABANAS Y COBIJAS",
        "SECAR ROPA",
      ],
    },
    {
      area: "PASILLOS",
      checks: [
        "BARRER",
        "TRAPEAR",
        "LIMPIAR PUERTAS COLINDANTES",
        "LIMPIAR MOBILIARIO COLINDANTE",
      ],
    },
    {
      area: "HABITACIONES",
      checks: [
        "LIMPIAR PROTECTORES IMPERMEABLES",
        "TENDER CAMAS CON SABANAS LIMPIAS",
        "BARRER",
        "TRAPEAR",
        "SACAR BASURA DE BOTES",
        "SACUDIR Y LIMPIAR CABECERAS DE CAMAS",
        "LIMPIAR CLOSET",
        "ORDENAR CLOSETS",
        "GUARDAR ROPA LIMPIA",
        "LIMPIAR Y SACUDIR MOBILIARIO GENERAL",
        "LIMPIAR VENTANAS",
      ],
    },
    {
      area: "BAÑOS DE HABITACIONES",
      checks: [
        "BARRER",
        "TRAPEAR",
        "LAVAR INODORO",
        "LAVAR LAVABO",
        "REVISAR ROLLO DE BAÑO",
        "LIMPIAR ESPEJOS",
        "LIMPIAR SILLAS DE BAÑO",
        "SACAR BASURA DE BOTES",
      ],
    },
    {
      area: "BAÑOS COMUNES",
      checks: [
        "BARRER",
        "TRAPEAR",
        "LAVAR INODORO",
        "LAVAR LAVABO",
        "REVISAR ROLLO DE BAÑO",
        "SACAR BASURA DE BOTES",
      ],
    },
    {
      area: "AREA DE EQUIPO Y EQUIPO",
      checks: [
        "BARRER",
        "TRAPEAR",
        "LIMPIAR SILLAS DE RUEDA, ANDADORES Y BASTONES",
      ],
    },
    {
      area: "JARDIN INTERIOR",
      checks: ["BARRER Y REGAR"],
    },
    {
      area: "JARDIN EXTERIOR",
      checks: ["BARRER Y REGAR"],
    },
  ];